src/civil/date.rs

This test comes from a [bug report to Temporal]. We assert the result we
get, and this also matches what Temporal does. But it does seem wrong to
me IMO. We defer fixing it for now and leave it be to be consistent with
Temporal.
[bug report to Temporal]: https://github.com/tc39/proposal-temporal/issues/2919

civil: add 'until' month test

---

COMPARE.md
src/timestamp.rs

The saturating methods *should* return an error. But I goofed on the
API. So at this point, our two choices are: leave it as-is, which
produces completely incorrect results when there are non-zero units of
days or greater, or panic when it occurs. I think a panic is better.
In Jiff 0.2, these APIs will be made fallible. And hopefully by then
we'll have truly infallible APIs that accept an "absolute" duration.
Partially addresses #36

timestamp: make saturating arithmetic panic for non-uniform units

---

src/span.rs

This PR dips our toes into the water of integration with
`std::time::Duration`. I do somewhat expect there to be more integration
points, particularly in the datetime arithmetic APIs, but this at least
paves a path for folks to _correctly_ convert between a `Duration` and a
`Span`. The error cases for the new APIs will ensure you can never
misuse these APIs.
This adds a few new APIs:
* `Span::is_positive`, since we already have `Span::is_negative` and
`Span::is_zero`.
* `Span::signum`, since it's signed and it's sometimes convenient.
* `TryFrom<std::time::Duration> for Span`.
* `TryFrom<Span> for std::time::Duration` that returns an error if
the span is negative or has non-zero units bigger than days.
* `Span::to_duration` that requires a relative date and can convert any
positive span …

span: add Span::to_duration and TryFrom impls for Duration

---

src/fmt/temporal/mod.rs

Just a small docs fix I noticed while browsing.
Use `s` for seconds at the end instead of `d` for days.

doc: correct span format example regex

---

src/civil/date.rs
src/civil/datetime.rs
src/civil/time.rs
src/lib.rs
src/span.rs
src/timestamp.rs
src/tz/offset.rs
src/zoned.rs
tests/lib.rs

This was bad timing. The lang team just stabilized (in nightly) a new
deny-by-default lint, named `ambiguous_negative_literals`, which
triggers an error for things like `-1.hour()`. While such things can be
confusingly ambiguous in some cases, in Jiff, `-1.hour()`, `(-1).hour()`
and `-(1.hour())` are all, very intentionally, precisely equivalent.
For now we just `allow` the lint. If the lint stays, we'll likely want
to recommend allowing it in the Jiff docs.
See: https://github.com/rust-lang/rust/pull/121364

span: allow `ambiguous_negative_literals`

---

src/span.rs

I noticed that at least [one person] was confused about what it should
return. In particular, the getters on a `Span` return the individual
units, and not the "total" amount of them in the entire span. This is
different from how "absolute" durations work that don't keep track of
the individual units in the span.
[one person]: https://lobste.rs/s/rnqlef/named_arguments_rust_if_you_want_them#c_iiap4n

span: improve docs for Span getters

---

CHANGELOG.md
src/fmt/rfc2822.rs
src/fmt/strtime/mod.rs

In the course of doing some experiments with using Jiff in `gix-date`, I
discovered that it currently relies on the fact that parsing RFC 2822
datetimes (and similar) does *not* do error checking if the date and
weekday are inconsistent. Prior to this PR, Jiff required that the
weekday and date were consistent. This PR adds APIs for skipping this
check.
For RFC 2822, this adds a new `relaxed_weekday` configuration on the
`DateTimeParser` builder.
For the strtime APIs, we achieve this by adding more granular accessors
and mutators on `BrokenDownTime`. So now folks can do this:
```
let tm = BrokenDownTime::parse("%a, %F", "Wed, 2024-07-27")?;
tm.set_weekday(None);
assert_eq!(tm.to_date().unwrap(), jiff::civil::date(2024, 7, 27));
```
Where the above succeeds even though 2024-07-27 was a …

fmt: add APIs for skipping weekday checking

---

CHANGELOG.md
src/fmt/offset.rs
src/fmt/strtime/format.rs
src/fmt/strtime/mod.rs
src/fmt/strtime/parse.rs
src/fmt/temporal/printer.rs
src/fmt/util.rs

This isn't supported in the analogous C APIs, but it turns out it was
supported in the `chrono` crate and was actually being used.
This adds two new directives, `%f` and `%.f`. The former always writes
out at least one digit (and parsing requires at least one digit) and
corresponds to the number of fractional nanoseconds. The latter includes
the leading `.` and is satisfied by the empty string. That is, if a `.`
isn't found when `%.f` is expected, then it is skipped entirely when
parsing. Similarly, when formatting, if there are no fractional seconds
(i.e., the subsecond component is `0`), then no fractional component is
written either.
It is expected that most use cases will reach for just `%.f`, since it
will just do the "right" thing without thinking much about it. For
example, …

fmt/strtime: support parsing and formatting fractional seconds

---

.github/workflows/ci.yml
CHANGELOG.md
Cargo.toml
Cross.toml
PLATFORM.md
README.md
jiff-wasm/.gitignore
jiff-wasm/Cargo.toml
jiff-wasm/README.md
jiff-wasm/lib.rs
src/lib.rs
src/now.rs
src/timestamp.rs
src/tz/db/bundled/mod.rs
src/tz/db/mod.rs
src/tz/db/zoneinfo/enabled.rs
src/tz/system/mod.rs
src/tz/system/unix.rs
src/tz/system/wasm_js.rs
src/util/cache.rs
src/zoned.rs
test-wasm

This PR basically makes the `wasm{32,64}-unknown-unknown` targets work
_almost_ out of the box. All you need to do is enable Jiff's new `js`
crate feature. This will cause Jiff to depend on `js-sys` and
`wasm-bindgen`. Jiff will then use Javascript APIs to determine the
current time and time zone.
This PR also includes a new long form guide, `PLATFORM.md`, which
describes Jiff's platform support in one central location. (Most
information is already in Jiff's API docs, but it's scattered in a
variety of places.)
Finally, this adds a `wasm32-unknown-unknown` test to CI courtesy of
`wasm-pack`. It just does a basic sanity check that the current time and
time zone can be retrieved.
Fixes #56

jiff: add robust WASM support

---

CHANGELOG.md
src/fmt/strtime/format.rs
src/fmt/strtime/mod.rs
src/fmt/strtime/parse.rs

Previously, `strptime` worked greedily. That is, specifiers like `%Y`
matched as many ASCII digits as possible, and then tried to parse all
of them into a year value.
But this meant that using `%Y%m%d` to parse something like `20240730`
couldn't work: `%Y` would consume all of `20240730` and then of course
fail since the value exceeds the year boundaries of Jiff.
Instead, we tweak how parsing works so that it only consumes the
maximum possible number of digits given its boundaries.
Fixes #62

fmt: improve strptime so that it can parse adjacent values more easily

---

src/civil/date.rs
src/civil/datetime.rs
src/civil/time.rs
src/fmt/strtime/mod.rs
src/timestamp.rs
src/zoned.rs

I'm not a native speaker, so maybe I'm missing something. But the suggested phrasing would be easier for me to understand. I paused for a second at the "of" in *"The format string uses a "printf" style of API where conversion …"* when I read the docs. I also added a hyphen, but that can also be removed again.

doc: minor correction: "printf"-style API

---

CHANGELOG.md
src/fmt/mod.rs
src/fmt/offset.rs
src/fmt/strtime/format.rs
src/fmt/strtime/mod.rs
src/fmt/temporal/printer.rs
src/fmt/util.rs

This PR fixes an issue with formatting fractional seconds with
fixed precision settings. For example, previously, when formatting
`1.123456789` with `%.3f`, it would emit `1.123456789`. But this should
be `1.123`.
We do a bit of refactoring to split integer and fractional formatting
apart. Previously, we were using one cursed formatter to handle both
cases. By splitting them apart, we simplify both.
Fixes #73

fmt: fix precision formatting

---

CHANGELOG.md
src/fmt/strtime/format.rs
src/fmt/strtime/mod.rs
src/fmt/strtime/parse.rs
src/lib.rs
src/zoned.rs

This matches the V specifier used by [Java's formatting/parsing
infrastructure][java format].
The motivation for this is to bring the strtime APIs to parity with
`jiff::fmt::temporal`. Namely, without an IANA time zone identifier, one
cannot correctly roundtrip a `Zoned` value.
Jiff does support `%Z` when formatting for printing time zone
abbreviations like `EDT` or `EST`, but since these are ambiguous, they
aren't supported while parsing. (Perhaps we should support parsing and
validating them though, especially in conjunction with a IANA time zone
identifier.)
When using `%V`, if there is no IANA time zone identifier, then the
offset without colons is used instead. To get an offset with colons, use
`%:V`.
[java format]: https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/tim …

fmt/strtime: add %V and %:V for formatting and parsing IANA time zone identifiers

---

CHANGELOG.md
src/fmt/temporal/mod.rs
src/fmt/temporal/parser.rs

Because Jiff spans (like Temporal durations) represent each unit
individually, and because ISO 8601 require the use of fractional seconds
to represent sub-second units, there is an inherent loss of fidelity
when spans are serialized to the ISO 8601 duration format.
For example, a Jiff span like `1 second 2000 milliseconds` is distinct from
`3 seconds` even though they represent the same amount of elapsed time.
These types of spans are unbalanced.
When a span like `1 second 2000 milliseconds` is ISO 8601 serialized,
it's turned into `PT3s` because there simply is no way to represent
greater-than-second durations in smaller-than-second units in the ISO
8601 duration format. So when `PT3s` is deserialized, Jiff of course has
no idea that `1 second 2000 milliseconds` was actually intended, …

fmt/temporal: fix parsing of spans like `PT843517081h`

---

.github/workflows/ci.yml
Cargo.toml
src/civil/date.rs
src/timestamp.rs
src/tz/tzif.rs

I was getting pretty tired of the long compile times in between test
runs. I thought they seemed particularly long for debug mode. It turns
out that I had actually set `opt-level = 3` for running tests. This was
because there were a select few tests that ran quite long in debug mode.
But iteration time is important, so I trimmed down those tests and
disabled optimizations. Tests run much more quickly now after making a
change to the source code.
We also add `cargo test --profile testrelease` to CI. This is just like
normal tests, but disables `debug_assertions`. Jiff has a lot of extra
stuff going on when `debug_assertions` are enabled due to its internal
ranged integer abstraction. So it's useful to run tests without all that
extra stuff too (reflecting what is intended to be run in …

test: disable optimizations when testing

---

src/util/common.rs

I noticed that the `days_in_month` function returns constant rangeints where the range of the value is just the exact value, so for example `v: 31, min: 31, max: 31`. If the idea of the tracked min and max values (in debug builds) is to ensure that the code will work with all possible values of the function in question, then this means we don't actually check the computation for all possible responses to `days_in_month`.
By changing the return values to always have a range with min 28 and max 31 we can ensure that all calculations will work with every month and year, instead of the specific one they are tested with.
A sidenote is that if one returns just a common `Day` value from `days_in_month`, which has min of 1 and max of 31, this will end up throwing an error from the …

jiff: Days in month rangeint should always have range 28-31

---

src/span.rs

Previously, we would report a range error when trying to use units of
days or greater in a span when adding to a `Timestamp`. But this error
doesn't really do a good job of explaining anything. It was a hold-over
from the days where I was using many different error types and it was
difficult to improve messages on an ad hoc basis. But now, we can just
write a message.
The error message doesn't explain *why* days-and-greater are banned, but
it's hard to fit all of that into an error. At some point, we just have
to rely on folks reading the docs.
Closes #90

span: improve invalid units error message

---

src/tz/posix.rs

The subsequent optimization of https://github.com/BurntSushi/jiff/pull/103
`dst_info_utc` returns None when `self.dst` is None, then `unwrap_or_else` will return the std offset as the result. 
The `let dt = Offset::UTC.to_datetime(timestamp);` takes a lot of time, but it isn't used when `self.dst` is None. So we can skip it when `self.dst` is None.
This code takes 30% time of `Zoned::new`, when TimeZone doesn't have DST(daylight saving time). So after this change, the performance of `instant_to_civil_datetime_static-Asia/Shanghai` is improved by 30% on my Mac.
The time changed from 99.3±1.35ns  to 68.4±5.85ns on my Mac, and following is the detailed result:
```
group                                                base/chrono-tzfile/                    base/chrono/ …
```

improvement: ReasonablePosixTimeZone#to_offset returns default value directly when dst is none

---

src/tz/tzif.rs

The subsequent optimization of https://github.com/BurntSushi/jiff/pull/103
binary_search_by_key find the index from transitions, when the timestamp is greater than all timestamp in transitions. It's not needed to binary search.
It always happens when some timezones had DST before, but DST is canceled for now.
Compare the timestamp with the biggest timestamp in `transitions`. If `timestamp > self.transitions.last().unwrap().timestamp`, we can avoid the binary search.
In biref, the performance of `instant_to_civil_datetime_static-Asia/Shanghai`  is improved 2 times via cthe urrent PR and #104 
The performance of `instant_to_civil_datetime_static-Asia/Shanghai `:
- `99.3±1.35ns` : Without current PR and #104
- `68.4±5.85ns` : master with #104
- `50.1±1.02ns` : With current PR and #104
``` …
```

improvement: to_offset avoids binary search if the timestamp is greatr than the biggest one

---

CHANGELOG.md
src/civil/date.rs
src/civil/datetime.rs
src/civil/mod.rs
src/civil/time.rs
src/civil/weekday.rs
src/duration.rs
src/fmt/temporal/mod.rs
src/fmt/temporal/parser.rs
src/fmt/temporal/printer.rs
src/lib.rs
src/now.rs
src/signed_duration.rs
src/span.rs
src/timestamp.rs
src/tz/mod.rs
src/tz/offset.rs
src/util/libm.rs
src/util/round/mode.rs
src/util/t.rs
src/zoned.rs

This PR adds a new top-level `SignedDuration` type to Jiff. This PR also
does the work to integrate it into all Jiff datetime APIs. For example,
`Zoned::checked_add` now accepts a `jiff::Span`, `jiff::SignedDuration`
or a `std::time::Duration`. To achieve this, we add a new target type,
`ZonedArithmetic`, with `From` trait implementations for each of the
corresponding duration types. We then changed the `span: Span`
parameter type to `duration: impl Into<ZonedArithmetic>`. We also add
new `Arithmetic` target types for each datetime type, for example,
`TimestampArithmetic`.
This design was chosen over using one target type shared across all
datetime types to allow for future extensibility. For example, maybe in
the future we want to add extra options to `Zoned::checked_add`. We can
now do …

api: add new top-level SignedDuration type

---

Cargo.toml

This matches a similar change made by @ChrisDenton for winapi-util in:
https://github.com/BurntSushi/winapi-util/pull/19
The benefit is that this should hopefully put less constraints on the
ecosystem and to enable fewer copies of windows-sys to appear in
dependency trees.
I am somewhat miffed that this is necessary. IMO, the windows-sys
maintainers should find a way to make a stable release with infrequent
or ~zero breaking change releases.

cargo: permit windows-sys >=0.52.0 and <=0.59.*

---

src/duration.rs
src/timestamp.rs
test

I was lured into a false sense of confidence with CI testing. Because
tests unconditionally enable `std`, this
cargo test --lib --no-default-features --features alloc
doesn't actually fail when there is an errant `std` reference. But this
does:
cargo build --no-default-features --features alloc
We fix our `test` script to catch this case and also fix the build
errors.
Fixes #108

cargo: fix alloc-only build

---

CHANGELOG.md
src/civil/datetime.rs
src/civil/time.rs
src/fmt/temporal/mod.rs
src/fmt/temporal/printer.rs
src/timestamp.rs
src/zoned.rs

This PR introduces new options for controlling the precision
of fractional seconds when printing `Zoned`, `Timestamp`,
`civil::DateTime` or `civil::Time` values. This is principally exposed
via `jiff::fmt::temporal::DateTimePrinter::precision`, but it's also
available via the standard library's formatting machinery. For example,
if `zdt` is a `jiff::Zoned`, then `format!("{zdt:.6}")` will format
it into a string with microsecond precision, even if its fractional
component is zero.
This is useful when one wants a datetime to use a "fixed width" format.
Or at least, as close to one as possible. For `Zoned` in particular, a
fixed width format is somewhat difficult to accomplish because of the
variable length IANA time zone identifier. But if the time zone
identifier is the same for all …

api: add options for controlling precision

---

CHANGELOG.md
src/tz/system/mod.rs
src/tz/system/unix.rs
src/tz/system/wasm_js.rs
src/tz/system/windows/mod.rs

Previously, we would only attempt to use symlink metadata when reading
from /etc/localtime explicitly. We didn't do this when `TZ` is set to a
path. And in particular, `TZ` might actually be set to `/etc/localtime`,
in which case, it's likely a symlink. And we can detect the IANA time
zone identifier from the symlink in most cases. Just like we would by
default if `TZ` wasn't set.
I originally didn't do this because the code for handling `TZ` was
actually completely platform independent, so it didn't occur to me to do
something platform specific on Unix. But it's not too hard to do.
While setting `TZ=/etc/localtime` is odd, apparently this is given as
advice to folks for libc to avoid repeatedly reading `/etc/localtime` to
check for updates. Seems weird to me, but whatever. Jiff should …

tz: attempt to read TZ symlink as IANA time zone identifier

---

src/zoned.rs

This PR adds a note to the `Zoned::now()` documentation describing the
best way to create a `Zoned` for the current time in a time zone that
isn't the system time zone. Unfortunately, one intuitive route is
`Zoned::now().with_time_zone()`, but this 1) fetches the system time
zone, which isn't free and 2) computes the civil datetime for the system
time zone, which is not necessary here. Instead,
`Timestamp::now().to_zoned()` is a more direct approach that doesn't do
any unnecessary work.
I decided to go this route instead of adding a new API as requested
in #93. In particular, I think the API suggested in #93 is a bit clunky,
and is likely to lead to the addition of other even clunkier APIs as
well. While using a `Timestamp` might require an extra import, it does
have the benefit of being …

zoned: add note about Timestamp::now().to_zoned()

---

src/util/libm.rs

During an internal review of unsafe code at work, @cramertj noticed that the the `force_eval!` can be replaced by `std::hint::black_box`, removing the need for unsafe Rust.

util/libm: replace `force_eval!` by `std::hint::black_box`

---

CHANGELOG.md
DESIGN.md
src/fmt/rfc2822.rs
src/fmt/temporal/mod.rs
src/fmt/temporal/printer.rs
src/lib.rs
src/timestamp.rs

This PR does a couple things.
First, it adds a new
`jiff::fmt::DateTimePrinter::print_timestamp_with_offset` routine for
formatting a `jiff::Timestamp` as an RFC 3339 string with a specific
offset. In particular, this draws a contrast between the existing
`print_timestamp` method which will always use Zulu time. (Zulu is UTC,
but where the offset is unknown.)
Secondly, we add new helper methods on the datetime and span printers
to format datetimes and spans directly into a string. This is just
for convenience, since otherwise creating a `String` and passing
it in as a buffer can be a bit annoying. Also, since it's fixed to
a `String`, these methods are infallible and can never fail, which
further simplifies their use.

fmt: support formatting `Timestamp` with a specific offset

---

CHANGELOG.md
src/tz/mod.rs

This API is like `TimeZone::system`, but turns "get system configured
time zone" into a fallible operation instead of automatically falling
back to UTC.
The error message here is pretty generic and uninformative. All of the
interesting bits are emitting as log messages. In #65, I talked about
improving this, but it's not quite clear the best way to do that. I
think we'd probably need to invent some smarter infrastructure for
collecting a "trace" of what was attempted, and then either emit them as
log messages or tie them up into a single error message. But the latter
case could result in a very big error message.
So for now, this just returns a pretty generic error message, but all of
the log statements are still there for when you need to understand more
deeply what went wrong.

tz: add `TimeZone::try_system`

---

src/fmt/util.rs

It turns out that "no padding set" and "padding is zero" result in the
same behavior. I think this might have been different back when I was
(ab)using the integer formatting to also do fractional formatting. But
either way, eliminating a redundant internal state is a win.
I discovered this while wondering whether I could unconditionally set
the padding to `0` and if it would be the same as not setting it.

fmt: simplify integer formatting slightly

---

src/util/escape.rs
src/util/mod.rs
src/util/utf8.rs

This moves UTF-8 decoding from an internal helper in
`jiff::util::escape` to a crate-wide helper in `jiff::util::utf8`.
This makes it easier for other code to use this. I may end up using it
for #111, for example.

util: move UTF-8 decoding to its own module

---

src/timestamp.rs

~~The end goal with this PR is to adjust the documentation to make the semantics of the library as clear as possible.~~
~~I've started with just a tiny change to set a foundation, updating the documentation comment to define Timestamp wrt UNIX time.~~
citations, since my only msgs so far are on discord (I believe Timestamp = Unix is currently intentional, this is just a mistake in docs):
- `now` uses the value constructed by `duration_since(EPOCH)`, which is [defined as POSIX time](https://doc.rust-lang.org/stable/std/time/struct.SystemTime.html#associatedconstant.UNIX_EPOCH)
> duration_since(UNIX_EPOCH).unwrap().as_secs() returns the number of non-leap seconds since the start of 1970 UTC. This is a POSIX time_t (as a u64), and is the same time representation as used in many Internet …

Tweak docs to update Timestamp definition to current behaviour

---

src/fmt/rfc2822.rs

It seems that RFC 9110 does not support offsets like `-0000` in the
date format, and also requires that days be padded to two digits in all
cases. This meant that Jiff's RFC 2822 output was, strictly speaking,
incompatible with a strict implementation of RFC 9110. For example, it
would output this:
Thu, 1 Jan 1970 00:00:01 -0000
Where RFC 9110 would want this:
Thu, 01 Jan 1970 00:00:01 GMT
I am actually still unclear as to the relationship between
RFC 2822/5322 and RFC 9110, but as far as I know, RFC 2822
has been obsoleted by RFC 5322, but RFC 5322 does not seem
to make any meaningful changes to the datetime format:
https://datatracker.ietf.org/doc/html/rfc5322#section-3.3
But, since it seems like the RFC 9110 format is a subset of the RFC
2822/5322 format, and since [MDN clearly …

fmt/rfc2822: add routines explicitly for RFC 9110

---

CHANGELOG.md
src/tz/mod.rs

api: add `TimeZone::to_fixed_offset`

---

Cargo.toml
src/error.rs
src/lib.rs
src/now.rs
src/span.rs
src/timestamp.rs
src/tz/db/bundled/enabled.rs
src/tz/db/zoneinfo/enabled.rs
src/tz/mod.rs
src/tz/posix.rs
src/tz/system/mod.rs
src/tz/tzif.rs
src/util/array_str.rs
src/util/cache.rs
src/util/mod.rs
src/util/parse.rs
src/util/round/increment.rs
src/zoned.rs
tests/tc39_262/span/round.rs
tests/tc39_262/span/total.rs

There is still a fair bit more to do to fully address #168, but this PR gets rid of some allocations
inside of `src/tz/posix.rs`. We weren't using them by necessity per se, but
it did simplify a fair bit.

reduce reliance on `alloc` crate in `src/tz/posix.rs`

---

src/fmt/mod.rs
src/fmt/rfc2822.rs
src/fmt/serde.rs
src/fmt/strtime/mod.rs
src/fmt/temporal/mod.rs
src/tz/mod.rs
src/tz/offset.rs
src/util/array_str.rs

This continues work from #179 to make progress on #168.

remove more allocations

---

.github/workflows/ci.yml
CHANGELOG.md
Cargo.toml
src/error.rs
src/lib.rs
src/tz/db/mod.rs
src/tz/mod.rs
src/tz/system/mod.rs
src/tz/zic.rs

Fixes #162
e.g. for esp32c3 and such you can see it building using
```
cargo build --target=riscv32imc-unknown-none-elf --features alloc --no-default-features --features portable-atomic/unsafe-assume-single-core
```

Support platforms that do not have native atomics

---

Cargo.toml
src/civil/date.rs
src/civil/iso_week_date.rs
src/error.rs
src/fmt/friendly/printer.rs
src/fmt/mod.rs
src/fmt/rfc2822.rs
src/fmt/rfc9557.rs
src/fmt/strtime/format.rs
src/fmt/strtime/mod.rs
src/fmt/strtime/parse.rs
src/fmt/temporal/mod.rs
src/lib.rs
src/span.rs
src/timestamp.rs
src/tz/db/bundled/disabled.rs
src/tz/db/mod.rs
src/tz/db/zoneinfo/disabled.rs
src/tz/db/zoneinfo/enabled.rs
src/tz/mod.rs
src/tz/posix.rs
src/tz/system/mod.rs
src/tz/testdata.rs
src/tz/zic.rs
src/util/borrow.rs
src/util/mod.rs
src/util/rangeint.rs
src/util/sync.rs
src/zoned.rs
test

There are a few main downsides to core-only support:
1. The error messages produced by Jiff are now awful.
2. Time zone integration is basically gone. All you get are fixed offset
time zones. Neither POSIX time zones nor IANA time zones are
supported.
3. The sizes of some types (e.g., `TimeZone` and `Zoned`) are now bigger
than they are when `alloc` is enabled.
It is possible (1) could be mitigated somewhat, but not entirely. One
way they could be improved is by using more structured error types
instead of strings at the point where the error occurs. When using
strings, some kind of interpolation is needed to convert it to a heap
allocated `String`. But if we used structured error types, we wouldn't
need this heap allocation in the vast majority of cases. However,
doing this is a major …

add core-only (no-std and no-alloc) support to Jiff

---

src/error.rs
src/span.rs
src/timestamp.rs

While this doesn't remove the arithmetic impls (I think that would be a
bridge too far), we try to make the docs a little clearer and slightly
improve the error message. The error message still doesn't say "why,"
but does hint at it a bit.
Closes #145

timestamp: improve docs surrounding arithmetic panics

---

CHANGELOG.md
src/fmt/strtime/mod.rs
src/tz/mod.rs
src/tz/posix.rs
src/tz/tzif.rs
src/util/array_str.rs
test

This adds new APIs for iterating over the preceding and following time
zone transitions from a particular point in time.
The hard work was something I actually did a bit ago, but I never
exposed, since I didn't want to figure out the API details. There's
actually a fair bit of information we can expose (timestamp, offset,
abbreviation and whether DST is active), so we introduce a new type,
`jiff::tz::TimeZoneTransition`, that wraps this all up.
Closes #144

tz: add `TimeZone::preceding` and `TimeZone::following` for iterating over time zone transitions

---

CHANGELOG.md
src/civil/date.rs
src/civil/datetime.rs
src/civil/time.rs
src/zoned.rs

Specifically, this puts harder and more explicit guarantees on the range
of values returned by methods like `year`, `month`, `day`, `hour` and so
on.
Fixes #130

doc: document the range of some values

---

CHANGELOG.md
src/fmt/strtime/format.rs
src/fmt/strtime/mod.rs

I'm not sure why I didn't do this initially. I think I thought there
wasn't a use case. But it's easy enough to support.
This would have probably been easier if we accepted a `&str` for the
format string, especially since we require valid UTF-8 (which is a
strict relaxation from requiring valid ASCII). In that case, we would
just iterate over `chars()`. But, that would require the caller to
create the `&str` (thus paying for UTF-8 validation) and would require
`strftime` to do UTF-8 decoding. This way, we don't require any of that
up-front UTF-8 validation, and in the vast majority of cases
(ASCII-only), we just handle things one-byte-at-a-time without caring
about UTF-8.
Fixes #155

fmt/strtime: support non-ASCII in `strftime` format strings

---

CHANGELOG.md
src/lib.rs
src/signed_duration.rs
src/span.rs
src/util/rangeint.rs

This adds a new `SignedDuration::round` method that behaves like `Span`,
but for time (non-calendar) units only.
For the most part, we just copy `Span::round` as-is, but without the
`largest` unit knob (which doesn't make sense for something like
`SignedDuration`) or the `relative` datetime knob (which isn't needed
for a duration with all invariant units, as is the case for
`SignedDuration`). We can even reuse the same implementation for `Span`
rounding: we convert the duration to a 128-bit signed integer of
nanoseconds, do the rounding and then convert back (and check for
overflow).
Note that we specifically don't both with adding rounding functionality
built into APIs like `Zoned::duration_since` or
`civil::DateTime::duration_until`, unlike what we do for `Span`, since
composition works …

signed_duration: add `round` method

---

CHANGELOG.md
COMPARE.md
src/civil/date.rs
src/civil/datetime.rs
src/civil/time.rs
src/fmt/friendly/mod.rs
src/fmt/friendly/parser.rs
src/fmt/temporal/mod.rs
src/fmt/temporal/printer.rs
src/lib.rs
src/signed_duration.rs
src/span.rs
src/timestamp.rs
src/zoned.rs
tests/tc39_262/civil/datetime/until.rs
tests/tc39_262/civil/time/until.rs
tests/tc39_262/span/round.rs

This somewhat revives #22, but makes it possible to restore the previous
behavior by enabling `jiff::fmt::temporal::SpanPrinter::lowercase`.
The main motivation here is also detailed in #22, and it came up again
in #188. I was previously reluctant to do this because I find
`P1Y2M3DT4H5M6S` hideously difficult to read and `P1y2m3dT4h5m6s`
somewhat less difficult to read. But now that `jiff::fmt::friendly` is a
thing and users have easy access to a more readable duration display
format, I feel less bad about this. It's still a shame that it's the
default via `span.to_string()`, but I tried to sprinkle a few
`format!("{span:#}")` in places to nudge users toward the friendly
format.
It's a shame more systems don't accept lowercase unit designator labels,
but since Jiff uses the ISO 8601 by …

temporal: use uppercase unit designator labels by default

---

CHANGELOG.md
src/fmt/offset.rs
src/fmt/rfc9557.rs
src/fmt/temporal/mod.rs
src/fmt/temporal/parser.rs
src/fmt/temporal/pieces.rs
src/fmt/temporal/printer.rs
src/lib.rs
src/tz/offset.rs
src/util/borrow.rs
src/zoned.rs

This commit adds a new type to the `jiff::fmt::temporal` module that
exposes the raw components of a parsed Temporal ISO 8601 datetime
string.
This is meant to address use cases that need something a bit more
flexible than what is provided by the higher level parsing routines.
Namely, the higher level routines go out of their way to stop you from
shooting yourself in the foot. For example, parsing into a `Zoned`
requires a time zone annotation.
But parsing into a `Pieces` doesn't require any of that. It just has
to match the Temporal ISO 8601 grammar. Then you can mix and match
the pieces in whatever way you desire. And indeed, you can pretty
easily shoot yourself in the foot with this API. I feel okay about this
because it's tucked into a corner of Jiff that you specifically have to
seek …

fmt/temporal: add new `Pieces` type for granular ISO 8601 parsing

---

CHANGELOG.md
src/fmt/friendly/printer.rs

This adds a new option for configuring the unit to use when formatting a
zero span or duration.
Closes #192

fmt/friendly: add "zero unit" option

---

src/fmt/rfc2822.rs

`fmt::rfc2822::DateTimePrinter::timestamp_to_rfc9110_string` allocates a `String` with capacity of `4`; however RFC 9110-preferred-format strings are guaranteed to have an exact length of 29. I realize this crate doesn't prioritize performance; however the fact that `String::with_capacity` was already used as opposed to `String::new` suggests this isn't an entirely inappropriate diff.

allocate exact capacity for RFC 9110 strings

---

.github/workflows/ci.yml
CHANGELOG.md
src/tz/system/android.rs

I guess some platforms use `*const u8` for C strings while most
seemingly use `*const i8`. So insert a bunch of `.cast()` calls where
appropriate.
Ref #140
Fixes #200

tz: fix termux compilation on Android

---

CHANGELOG.md
Cargo.toml
jiff-tzdb-platform/Cargo.toml
jiff-tzdb/Cargo.toml

When 6926d6d84fb685ded50816fa525ee147e43aaff4 explicitly listed files to include in published crates, the license files were lost from the crates. This PR restores them by adding them to the `include` lists.

Restore license files that were lost in 0.1.22

---

CHANGELOG.md
src/civil/date.rs
src/civil/datetime.rs
src/civil/iso_week_date.rs
src/zoned.rs

This PR rolls up #196 and adds some convenience `iso_week_date` methods
to `Zoned` and `DateTime`. These forward to the corresponding method on
`Date`.
Also, to make naming more consistent, we deprecate
`Date::to_iso_week_date` and add `Date::iso_week_date`. The `to_`
prefix is somewhat inconsistently used in Jiff. According to Rust API
guidelines, it should probably be used a lot more, since some APIs
that look like getters are actually doing a little bit of work. But I
think the API reads overall better by just dropping the `to_` prefix.
Using the `to_` prefix also has the problem of exposing aspects of the
implementation which could change over time.
Finally, we add corresponding `From` impls for converting `DateTime`
and `Zoned` values into a `ISOWeekDate`.
Closes #196, Closes #197

add `iso_week_date` methods, deprecate `to_iso_week_date`

---

src/civil/date.rs
src/civil/datetime.rs
src/timestamp.rs

Current docs for `civil::DateTime::to_zoned` link to itself for the use case of parsing a string into a time zone. `civil::DateTime::intz` seems more appropriate.

Fix incorrect doc link

---

CHANGELOG.md
src/civil/iso_week_date.rs

I think this helps make the naming a little more consistent.
We still have `Date::to_zoned` and `Date::to_datetime` (instead of just
`Date::zoned` and `Date::datetime`), but I think those makes sense. At
least, it feels wrong to drop the `to_` prefix there.
I honestly kind of feel like `Date::to_iso_week_date` and
`ISOWeekDate::to_date` are also right, but for `Zoned`,
`to_iso_week_date` makes less sense? And I want `Zoned` to use the same
names of methods that are available on `DateTime` and `Date`.

civil: deprecate `ISOWeekDate::to_date()` in favor of `date()`

---

CHANGELOG.md
src/fmt/strtime/mod.rs

I had always intended to expose the ability to parse a prefix of some
string via Jiff's `strptime`-like API, but I wanted a use case first to
make sure the API was well motivated. So this is mostly just exposing
what was already there and documenting it.
Closes #209

fmt/strtime: expose prefix parsing

---

CHANGELOG.md
src/timestamp.rs
src/zoned.rs

When doing timestamp arithmetic, we were special casing a path where if
there weren't any fractional seconds, could skip a fair bit of math.
However, we were only checking whether the span given lacked fractional
seconds. We also need to check if the timestamp does. If either have
non-zero fractional seconds, then we can take the optimized path. This
was resulting in apparent precision loss.
Fixes #223

timestamp: fix precision loss in arithmetic

---

CHANGELOG.md
Cargo.toml
src/civil/date.rs
src/civil/datetime.rs
src/civil/time.rs
src/signed_duration.rs
src/span.rs
src/timestamp.rs
src/zoned.rs

... and replace it with serde-yaml. This is non-ideal since serde-yaml
is deprecated, but I'll take that over the shenanigans going on with
serde-yml (that I was unaware of, since this was a dev-dependency).
Ref https://x.com/davidtolnay/status/1883906113428676938

dev-dependencies: remove dependency on serde-yml

---

CHANGELOG.md
src/civil/iso_week_date.rs

This PR adds the following methods to `jiff::civil::ISOWeekDate`:
* `ISOWeekDate::first_of_week`
* `ISOWeekDate::last_of_week`
* `ISOWeekDate::first_of_year`
* `ISOWeekDate::last_of_year`
* `ISOWeekDate::days_in_year`
* `ISOWeekDate::weeks_in_year`
* `ISOWeekDate::tomorrow`
* `ISOWeekDate::yesterday`
This makes it a bit easier to navigate around the calendar without
having to do this manually.
In #227, I originally proposed adding `ISOWeekDate::series` as well, but
as I implemented it, I think it turned out to be a bad idea. In
particular, `Span` is really a _Gregorian_ period of time, and applying
it to `ISOWeekDate` can be awkward. It works fine for units of weeks or
lower, but above it's weird. For months, one might excuse it since it's
"obvious" that a month will be applied on the …

civil: add convenience routines for ISOWeekDate

---

CHANGELOG.md
src/fmt/mod.rs
src/fmt/offset.rs
src/fmt/rfc9557.rs
src/fmt/serde.rs
src/fmt/temporal/mod.rs
src/fmt/temporal/parser.rs
src/fmt/temporal/printer.rs
src/tz/mod.rs
src/tz/posix.rs
src/tz/system/mod.rs
src/util/escape.rs

And, also, add lower level routines to `jiff::fmt::temporal` for
printing and parsing a `TimeZone` without going through Serde.
For now, we don't implement `Serialize` or `Deserialize` on `TimeZone`
directly. Instead, we add `with` helpers to `jiff::fmt::serde::tz`. This
is because it's not clear if this is an appropriate "universal"
serialization for a `TimeZone`, and especially since for some (very
rare) cases, a `TimeZone` cannot be serialized succinctly. I also think
it's somewhat _odd_ that a `Deserialize` routine will do an implicit
global tzdb lookup. But it's not really clear that that is an issue in
practice, especially since we're already doing that for parsing `Zoned`
values.
Closes #89

tz: add support for (de)serializing `TimeZone` with Serde

---

CHANGELOG.md
src/fmt/temporal/parser.rs
src/signed_duration.rs
src/tz/mod.rs
src/tz/offset.rs
src/tz/posix.rs

This adds a new `Offset::round` API in order to support fixing #231.
Namely, previously, we would fail to parse zoned datetimes
like `1969-12-31T23:15:30-00:45[Africa/Monrovia]` because
`Africa/Monrovia`'s offset at the time was `-00:44:30`, which doesn't
match `-00:45:00`. This in turn caused an error because Jiff's default
behavior is to reject parsed datetimes whose offset doesn't match a
valid offset in the corresponding time zone.
However, in this case, we want to accept it. What it comes down to
is that RFC 3339 and RFC 9557 do not support fractional minutes in
the offset. (I wonder why they flubbed that one.) So in order to
be compatible with existing implementations, Jiff serializes zoned
datetimes with fractional minutes by rounding to the nearest minute.
Hence why you might see …

tz: add `Offset::round` and fix `Africa/Monrovia` parsing

---

.github/workflows/ci.yml
Cargo.toml
crates/jiff-icu/COPYING
crates/jiff-icu/Cargo.toml
crates/jiff-icu/LICENSE-MIT
crates/jiff-icu/README.md
crates/jiff-icu/UNLICENSE
crates/jiff-icu/src/error.rs
crates/jiff-icu/src/lib.rs
crates/jiff-icu/src/traits.rs

(This is still a WIP, but I think all of the trait impls that make sense
to add in `icu 1.5` are here. Mostly I just have docs to write.)
This adds a new crate, `jiff-icu`, with `ConvertFrom` and `ConvertInto`
traits. These mirror the `TryFrom` and `TryInto` traits from `std`. I
took this approach for conversions specifically because it avoids
needing to define wrapper types for everything. It does means we can't
use the standard traits, but I think just importing one trait and having
that add conversion routines on to the types in `jiff` and
`icu_calendar` is an overall lighter weight solution.
One thing I'm slightly unsure about is whether I want `jiff-icu` to just
encompass _everything_ that makes sense to convert between inside of
`icu`, or whether it should actually be …

jiff-icu: add crate for converting to-and-from `icu_calendar`

---

crates/jiff-diesel/src/mysql.rs
crates/jiff-diesel/src/postgres.rs
crates/jiff-diesel/src/sqlite.rs
crates/jiff-diesel/src/wrappers.rs

This reduces the amount of boilerplate code needed for each wrapper type. In addition, the implementation is more general, allowing external implementations of `Backend` to use `Queryable`.
Example expansion:
```rust
const _: () = {
use diesel;
use diesel::deserialize::{self, FromSql, Queryable};
impl<__DB, __ST> Queryable<__ST, __DB> for Timestamp
where
__DB: diesel::backend::Backend,
__ST: diesel::sql_types::SingleValue,
Self: FromSql<__ST, __DB>,
{
type Row = Self;
fn build(row: Self::Row) -> deserialize::Result<Self> {
Ok(row)
}
}
};
```

jiff-diesel: Derive the `Queryable` trait for diesel wrapper types.

---

crates/jiff-diesel/Cargo.toml

Fixes errors like:
```
error[E0277]: the trait bound `jiff::Error: std::error::Error` is not satisfied
--> crates/jiff-diesel/src/mysql.rs:31:51
|
31 |             dt = dt.round(jiff::Unit::Microsecond)?;
|                                                   ^ the trait `std::error::Error` is not implemented for `jiff::Error`
|
= help: the trait `FromResidual<Result<Infallible, E>>` is implemented for `Result<T, F>`
= note: required for `Box<dyn std::error::Error + Send + Sync>` to implement `From<jiff::Error>`
= note: required for `Result<IsNull, Box<dyn std::error::Error + Send + Sync>>` to implement `FromResidual<Result<Infallible, jiff::Error>>`
```

jiff-diesel: Diesel error needs to implement std Error, add std feature to jiff.

---

crates/jiff-diesel/Cargo.toml

Diesel splits the mysql implementation between the `mysql_backend` feature which implements the types/traits/etc., and the `mysql` feature which also interfaces with the mysql client library. By depending on the backend feature, we can avoid pulling in the mysql library dependency when it's not needed (e.g. using diesel-async).
Similarly for `postgres` and `postgres_backend`.

jiff-diesel: Depend on postgres_backend and mysql_backend.

---

examples/diesel-mysql/main.rs
examples/diesel-postgres/main.rs
examples/diesel-sqlite/main.rs

Updated examples for diesel that exercise a more usual usage of the library (when manually writing SQL), and also test the `deserialize_as` annotation for the wrapper type.

jiff-diesel: Update diesel examples to use QueryableByName and sql_query.

---

crates/jiff-diesel/src/lib.rs
crates/jiff-diesel/src/nullable.rs
examples/diesel-postgres/main.rs

Adds Nullable wrappers for Diesel types. This allows the use of `Option<T>` in structs used in diesel queries/updates/etc., where `T` is a supported jiff type. Leverages existing jiff wrapper implementations, so it just forwards through (de)serialization to the already written types.
Currently this PR is built on top of PR #247, will rebase after (if) that is merged.
Also, you may want to do some reorganization, documentation updates, etc. Comment here, and I'll fix, or you can update the branch. 
It does not support using these wrapper types as expressions (e.g. filter, group by, etc.). In these cases, use `Option<jiff_diesel::WrapperType>`.
Fixes issue #246.

jiff-diesel: Add Nullable wrappers for Diesel types.

---

CHANGELOG.md
COMPARE.md
Cargo.toml
crates/jiff-diesel/Cargo.toml
crates/jiff-diesel/README.md
crates/jiff-icu/Cargo.toml
crates/jiff-icu/README.md
crates/jiff-sqlx/Cargo.toml
crates/jiff-sqlx/README.md
src/fmt/friendly/mod.rs
src/fmt/mod.rs
src/fmt/strtime/mod.rs
src/lib.rs
src/span.rs
src/tz/mod.rs

This is doing some final touch-ups to prepare for the `jiff 0.2`
release. Most of these touch-ups are (and will be) docs related I
think.

prepare for `jiff 0.2` release

---

examples/diesel-mysql/main.rs
examples/diesel-postgres/main.rs
examples/diesel-sqlite/Cargo.toml
examples/diesel-sqlite/main.rs

This moves the majority of examples to use the `Insertable` and `Selectable` derivations from the query struct. This follows idiomatic Diesel usage. It also tests actual database round-tripping via database stores, includes testing of the `AsExpression` implementations.
The downside of this is that tables need to exist; I have created temporary tables in this PR for this purpose (which are dropped when the session is closed).
It also moves the database schema definition to a separate module, to match standard usage in diesel.
These tests require that #253 is merged, otherwise it's impossible to derive `Insertable` for nullable jiff types.

jiff-diesel: Update examples to use Insertable and Selectable derivations.

---

CHANGELOG.md
src/civil/datetime.rs
src/civil/time.rs
src/zoned.rs

For example, there is `Time::nanosecond` and `Time::subsec_nanosecond`.
The former sets the individual nanosecond component and does not change
the millisecond or microsecond components. But the latter sets the
entire fractional second component to nanosecond precision.
Fixes #261

doc: beef up docs for methods that set sub-second units

---

.github/workflows/ci.yml

The jobs that run `./test`, which test a bunch of different feature
combinations, take quite some time. I think a lot of that time is just
spent compiling the different feature combinations. But I suspect we are
also spending a lot of time running doc tests.
So this switches to Rust 2024 *just* for the jobs that run `./test`.

ci: try to speed up CI

---

CHANGELOG.md
crates/jiff-diesel/src/lib.rs
crates/jiff-sqlx/src/lib.rs
src/timestamp.rs

... and also add a "Crate features" section to the crate docs of
`jiff-sqlx` and `jiff-diesel`.
Fixes #273, Fixes #277

doc: clarify error conditions in `Timestamp` constructors

---

.github/workflows/ci.yml
crates/jiff-static/shared/mod.rs
crates/jiff-static/shared/tzif.rs
src/lib.rs

This should help ensure that generated code doesn't get stale.
This is especially pertinent with the new `src/shared` module, which has
to be copied over to `crates/jiff-static/shared` any time a change is
made. Not all changes result in breakage (theoretical or otherwise), so
it's easy to forget to do.

ci: check that `jiff-cli generate` doesn't produce diffs

---

.github/workflows/ci.yml
scripts/test
scripts/test-all
scripts/test-default
scripts/test-only-bundle
scripts/test-only-core
scripts/test-various-feature-combos
scripts/test-wasm
src/fmt/friendly/parser.rs
src/fmt/friendly/printer.rs
src/fmt/rfc2822.rs
src/fmt/strtime/format.rs
src/fmt/strtime/parse.rs
src/fmt/temporal/parser.rs
src/fmt/temporal/printer.rs
src/zoned.rs

It is tempting to think of this method as just being a shortcut for
`zdt.timestamp().subsec_nanosecond()`, but it actually isn't! It's
returning the fractional seconds on the *civil* datetime, not the
timestamp. These are usually the same for times after the Unix epoch,
but can differ for times before it.
While the original request in #283 asks for `subsec_millisecond()` and
`subsec_microsecond()` on `Zoned` in order to be consistent with
`Timestamp`, I'm going to pass on those for now. In particular, since
these would return the fractional second value from the *civil*
datetime, `subsec_millisecond()` would always be equivalent to
`millisecond()`. `subsec_microsecond()` wouldn't be the same as
`microsecond()` (just like `subsec_nanosecond()` isn't the same as
`nanosecond()`), but I find …

zoned: improve docs for `Zoned::subsec_nanosecond`

---

CHANGELOG.md
src/shared/util/itime.rs
src/zoned.rs

Basically, it was wrong when the date was the first day of the month.
This only impacts `jiff 0.2.2`. The bug wasn't present in previous
releases.
This was a transcription error during one of my refactors and it looks
like there unfortunately wasn't test coverage for it. Test coverage has
been added in this PR.
Fixes #290

shared: fix implementation of `IDate::yesterday`

---

src/shared/mod.rs
src/tz/timezone.rs

When I originally wrote the comment on `Repr`, I got the alignment
wrong. But I caught that mistake and fixed it before merging anything
to `master`. I just hadn't updated the comment.
The `repr(align(..))` was leftovers from experimenting with a
`TzifDateTime` that *wasn't* packed. I was trying to get `rustc` to
optimize comparisons automatically to a single integer, but couldn't get
ti to work. So I resorted to bit-packing. Since the representation is
now just an `i64`, an explicit alignment is not needed. (And it didn't
help anyway.)

tz: fix comment and remove superfluous `repr(align(..))`

---

src/civil/datetime.rs
src/zoned.rs

Specifically, that you can't get any units bigger than hours *by
default*.
We also fix what was probably a copy-and-paste error in the `Sub` trait
implementation docs for `Zoned`. (I probably copied it from
`jiff::civil::DateTime`, where it can return days by default.)
And we apply similar clarifications to the `jiff::civil::DateTime` docs
as well.
Ref https://github.com/microsoft/openvmm/pull/1028#discussion_r1994483092

doc: clarify the guaranteeds for `Zoned::{since,until}`

---

src/span.rs
src/util/borrow.rs

Quick fix - there's no need to actually clone the underlying dates, since we can simply borrow them.

span: avoid cloning when rounding

---

CHANGELOG.md
src/civil/datetime.rs
src/util/round/mode.rs
src/zoned.rs

Previously, if one were to round `2025-03-09T12:15[America/New_York]`
using the defaults (the half-expand rounding mode), then it would round
up to 2025-03-10. This is despite 2025-03-09 only being 23 hours long,
and thus, the tip-over point for rounding is actually 12:30 and not
12:00. Namely, at 12:00 on 2025-03-09, it had only been 2025-03-09 for
11 hours and not 12 hours.
This sort of rounding requires a special path that wasn't handled
correctly by civil datetime rounding. Interestingly, I had previously
been feeding the day length (which is 23 hours for the aforementioned
example) into civil datetime rounding, but it seems that it wasn't
actually doing anything. So I've ripped that out and special cased
rounding `Zoned` to the nearest day (following Temporal's lead).
I discovered …

zoned: fix rounding to "days" when near a time zone transition

---

CHANGELOG.md
src/civil/date.rs
src/shared/util/itime.rs
src/util/rangeint.rs

This also removes the error prone `transpose` functions I had added to
the bridge between the internal non-ranged datetime types and the ranged
datetime types.
Fixes #312

civil: fix `Date::nth_weekday_of_month`

---

CHANGELOG.md
src/tz/db/zoneinfo/enabled.rs

Apparently Illumos uses a different directory than most other Unix
systems in active use. So add it to the list of directories to scan.
I've been unable to verify this since I don't know how to run in an
Illumos environment, but hopefully this should work.
Fixes #315

tz: add `/usr/share/lib/zoneinfo`

---

.github/workflows/ci.yml
.gitignore
.vim/coc-settings.json
CHANGELOG.md
Cargo.toml
crates/jiff-diesel/Cargo.toml
crates/jiff-icu/Cargo.toml
crates/jiff-sqlx/Cargo.toml
examples/diesel-mysql/Cargo.toml
examples/diesel-postgres/Cargo.toml
examples/diesel-sqlite/Cargo.toml
examples/sqlx-postgres/Cargo.toml
examples/sqlx-sqlite/Cargo.toml
examples/uptime/Cargo.toml
rustfmt.toml
scripts/test-examples
scripts/test-integrations

I'm not sure when or how exactly it happened, but in the last weeks,
I've noticed that `rustc` gets effectively stun-locked whenever I make a
change to a source file in Jiff. A quick examination of what the fuck my
computer is doing seems to reveal that it's spending oodles of time
compiling diesel over and over.
I have no idea why this is happening and I don't really care to spend
the time unraveling the mysteries of diesel.
So I took a hammer to the problem. I have effectively shunted all
examples and all "integration" crates out of Jiff's core workspace and
into their own little bloated fiefdoms. To compensate for the fact that
`cargo test --all` no longer tests these things, I've added shell
scripts to run the requisite tests. And those shell scripts are now run
in CI.
I'm now back to …

cargo: restore sanity to iterative development

---

src/tz/system/mod.rs

This PR makes an empty `TZ` environment variable act like `TZ=UTC`. Should there be a unit test for this?
Fixes #311

Use UTC timezone then TZ env var is empty

---

.github/workflows/ci.yml
CHANGELOG.md
Cargo.toml
crates/jiff-cli/cmd/generate/shared.rs
crates/jiff-static/src/shared/mod.rs
crates/jiff-static/src/shared/posix.rs
crates/jiff-static/src/shared/util/itime.rs
src/civil/date.rs
src/civil/datetime.rs
src/civil/iso_week_date.rs
src/civil/time.rs
src/duration.rs
src/error.rs
src/fmt/friendly/parser.rs
src/fmt/offset.rs
src/fmt/rfc2822.rs
src/fmt/strtime/mod.rs
src/fmt/strtime/parse.rs
src/fmt/temporal/parser.rs
src/fmt/util.rs
src/lib.rs
src/shared/util/itime.rs
src/signed_duration.rs
src/span.rs
src/timestamp.rs
src/tz/offset.rs
src/tz/zic.rs
src/util/parse.rs
src/zoned.rs

This PR removes some generics on internal APIs. This very modestly
improves compile times in release mode in a simple test. Specifically,
I had:
```rust
fn main() {
println!("{}", Zoned::now());
}
```
with a dependency on `jiff`. Then I did `cargo clean && time cargo b
-r` to measure compilation time.
I also added a `perf-inline` crate feature that allows disabling all
uses of `inline(always)` inside of Jiff. It is enabled by default
though.

rustc: slightly improve compile times and add `perf-inline` crate feature

---

CHANGELOG.md
src/fmt/temporal/parser.rs
src/signed_duration.rs

This also resulted in a panic for an undocumented case, in debug mode, in
`SignedDuration::from_secs_f64`.
A similar fix has been applied to the `f32` case as well.
The problem was that if the fractional part of the floating point
duration rounded up to 1, then the nanosecond component would represent
a single full second. This case wasn't correctly accounted for.
This also adds an "alternate" `Debug` implementation for `SignedDuration`.
The alternate impl is a more "straight forward" representation of a
`SignedDuration`'s internals. That is, it just shows seconds and nanoseconds
(omitting zero components). I find this much easier to read when reasoning
about `SignedDuration`, since its internals and, to an extent, its API, are
defined in terms of its second and nanosecond components. …

signed_duration: fix panic in `SignedDuration::try_from_secs_f64`

---

src/signed_duration.rs

I was idly browsing recent PRs on Jiff and noticed what seems to be a docs typo on a regression test. It was introduced in #324.
It's obviously a tiny thing, but I thought I might as well fix it as soon as I spotted it.
If I've misunderstood, and it's not a typo, sorry for the noise.

Correct regression test comment from #324

---

CHANGELOG.md
src/now.rs

Suggested here: https://github.com/BurntSushi/jiff/issues/296#issuecomment-2718942045
I quickly put together a hello-world `trunk` project, and called `jiff::Zoned::new()` in it, without the `js` feature enabled.
<details><summary>The resulting panic</summary>
```
panicked at /home/dev/jiff/src/now.rs:30:9:
getting the current time in wasm32-unknown-unknown is not possible, enable jiff's `js` feature if you are targeting a browser environment
Stack:
__wbg_get_imports/imports.wbg.__wbg_new_8a6f238a6ece86ea@http://127.0.0.1:8080/trunk-hello-world-39605882ec2e39d8.js:246:21
trunk_hello_world-a7f87d88668d9124.wasm.__wbg_new_8a6f238a6ece86ea externref shim@http://127.0.0.1:8080/trunk-hello-world-39605882ec2e39d8_bg.wasm:wasm-function[2337]:0xace89 …
```

Panic on `wasm32-unknown-unknown` without `js` feature

---

CHANGELOG.md
src/util/rangeint.rs

Only the actual value matters. By deriving `Hash`, it was including the
tracked min/max values, which is of course incorrect.
Note that this was only an issue in debug mode. In release mode, the
min/max values aren't compiled in, and so the `Hash` impl was correct.
Fixes #330

rangeint: implement `Hash` for ranged integers manually

---

src/fmt/strtime/mod.rs

Coming from chrono, I was looking for an equivalent to `parse_and_remainder`, and found a small typo in `jiff::fmt::strtime::BrokenDownTime::parse_prefix` on the way.
Thanks for the crate! I am having fun using it in my projects :)

doc: fix typo

---

crates/jiff-sqlx/Cargo.toml
crates/jiff-sqlx/src/postgres.rs
crates/jiff-sqlx/src/sqlite.rs
scripts/test-integrations

This PR removes the dependency on `sqlx-core` for `jiff-sqlx`. This also enables the `std` feature for `jiff` by default  (which enables the `std::error::Error` impl) because `sqlx::Encode` and `sqlx::Decode` can only return a `Box<dyn Error>` as the error type.
Fixes #322

jiff-sqlx: remove dependency on sqlx-core

---

CHANGELOG.md
bench/src/print.rs
crates/jiff-icu/Cargo.toml
crates/jiff-icu/src/error.rs
crates/jiff-icu/src/lib.rs
scripts/test-integrations
src/error.rs
src/fmt/strtime/format.rs
src/fmt/strtime/mod.rs
src/fmt/strtime/parse.rs
src/fmt/util.rs
src/lib.rs

The ICU4X project seems to be slowly working toward a 2.0 release. It
is currently on `beta.2`. There are some nice improvements here, in
particular, the ability to localize zoned datetimes.
This PR migrates to ICU4X 2.0 (first commit) and then adds support for
conversions between time zones, offsets and zoned datetimes (second
commit). I've also added a basic example demonstrating how to format a
`jiff::Zoned` value.
I've also added support for `%c`, `%r`, `%X` and `%x` to `jiff::fmt::strtime`.
Since I have no plans for Jiff to do localization, and since these specifiers
are commonly implemented via localization, I've added some
infrastructure to `jiff::fmt::strtime` that enables overriding the behavior
of these specifiers. Specifically, in Biff (not yet released), I've used this
trait …

migrate `jiff-icu` to ICU4X 2.0 (beta 2), add `Custom` trait for hooking localization into Jiff's `fmt::strtime` APIs, optimize `strftime`

---

CHANGELOG.md
src/tz/db/bundled/enabled.rs
src/tz/db/concatenated/enabled.rs
src/tz/db/mod.rs
src/tz/db/zoneinfo/enabled.rs
src/tz/timezone.rs

Previously, this was not being special cased, which in turn read `UTC`
like any other time zone. But really, we should be returning
`TimeZone::UTC` when and if we know that the time zone is actually
`UTC`.
Fixes #346

tz: make bundled database return `TimeZone::UTC` when appropriate

---

CHANGELOG.md
src/fmt/offset.rs
src/fmt/strtime/format.rs
src/fmt/strtime/mod.rs
src/fmt/strtime/parse.rs

These are also motivated by their presence in GNU date. They are
basically just different ways of printing offsets from UTC.
We do some light refactoring to DRY up the code a bit, and to make it a
little nicer to handle a variable number (up to a fixed size limit) of
`:` characters preceding a directive.
This is honestly just a giant clusterfuck (who thinks having `%z`,
`%:z`, `%::z` and `%:::z` is a nice user experience!?!?), but so is
`strptime`/`strftime` I guess. Oh well.
Closes #342

fmt/strtime: add support for `%::z` and `%:::z`

---

CHANGELOG.md
src/fmt/strtime/format.rs
src/fmt/strtime/mod.rs

This is another (IMO) cursed API meant to provide some measure of
compatibility with GNU date: a mode that specifically ignores errors
when formatting datetimes using `jiff::fmt::strtime`.
For example, neither `%0` nor `%+` are valid conversion specifiers
supported by Jiff. By default, using those will result in an error. But
with the new lenient mode (which you need to opt into), no error will
occur and instead `%0` and `%+` just get written literally as-is in the
returned string.
This applies to other kinds of errors. For example, if you use `%z` with
a `BrokenDownTime` that doesn't contain an offset, then that would
normally result in an error. But in lenient mode, it just results in
`%z` being written literally.
The docs for this mode contain a strongly worded warning to avoid …

fmt/strtime: add "lenient" mode for `strtime` formatting APIs

---

CHANGELOG.md
src/fmt/rfc2822.rs

RFC2822 allows some unusual whitespace configurations which weren't covered previously. In particular, these two cases are now handled properly according to spec:
(1) Whitespace is allowed, but may also be completely omitted, on both sides of the `,` following the weekday;
(2) Whitespace is allowed around the time separators (`:`).
Fixes #339
---
1. I changed `skip_whitespace` to return a `bool` whether whitespace was actually encountered. This saved some extra checks in parsing the time, and made `parse_whitespace` slightly cleaner.
1. I'm not that familiar with advanced error handling in Rust (`.with_context`), but I tried my best to keep the same errors as before.
1. I added an extra test to ensure there's whitespace between the time (in minute precision) and timezone. This is easy to …

fmt/rfc2822: fix handling whitespace at comma and time separators

---

CHANGELOG.md
src/fmt/offset.rs
src/fmt/temporal/parser.rs
src/tz/offset.rs
src/zoned.rs

Previously we were allowing this through since we didn't distinguish
between `-00:45` and `-00:45:00` when checking offset equality. In the
former case, we round the actual offset (which is `-00:44:30` in this
case), and if it matches the provided offset, we allow it. But in the
latter case, we *should* respect the precision specified in the string
and perform exact equality.
We fix this by just querying the parsed structure to see if a second
component was actually parsed or not. If it was, we do exact equality.
(For context, this is only an issue because Temporal, and also Jiff,
generally only support time zone offsets up to minute precision when
formatting. This reflects what RFC 3339 and RFC 9557 support. However,
we still support *parsing* offsets with sub-minute precision. To make …

fmt/temporal: ensure that `1970-06-01T00-00:45:00[Africa/Monrovia]` does not parse successfully

---

CHANGELOG.md
src/fmt/rfc2822.rs

Skipping whitespace happens immediately before `input[0]`. But skipping
the whitespace could lead to `input` being empty.
We handle the empty case and add a regression test.
Fixes #359

fmt/rfc2822: fix panic in handling of whitespace

---

PLATFORM.md
src/tz/mod.rs
src/zoned.rs

This just fixes some errors I found in the prose when re-reading some of
it.
This also adds some `Zoned::start_of_day` test cases from
https://github.com/tc39/proposal-temporal/issues/3110

doc: some minor clean-ups

---

CHANGELOG.md
scripts/test-various-feature-combos
src/error.rs

The problem was an incorrect `cfg`. And, of course, that this feature
combination wasn't being tested. That has been fixed too.
Fixes #365

cargo: fix compilation when only `tzdb-concatenated` is enabled

---

.github/workflows/ci.yml
CHANGELOG.md
src/tz/db/mod.rs
src/tz/db/zoneinfo/enabled.rs
tests/init/mod.rs
tests/lib.rs

Specifically, this improves performance in the case of
`/usr/share/zoneinfo` being on a slow file system. Namely, #366 reports
cases (in CI) where this initialization could take multiple seconds.
In this commit, we remove the file reads---but keep the directory
traversal---for validating files in `/usr/share/zoneinfo` as TZif data.
Namely, it is common that while _most_ files in a zoneinfo directory are
valid TZif, not all are.
The reason for keeping the initial directory traversal is that it
simplifies the implementation for case insensitive time zone identifier
lookups. Without the IDs in memory, doing a case insensitive lookup on
the file system becomes much harder. Especially since IANA time zone
identifiers use mixed case and I believe there is no algorithmic way to
normalize them. …

tz: improve performance of initial `Zoned::now()`

---

.github/workflows/ci.yml
Cargo.toml
src/tz/db/zoneinfo/enabled.rs
tests/init/mod.rs
tests/lib.rs

While in #370 my tests indicated that the slowest tzdb init was still
under ~33ms, right after it merged to master, I saw a spike to 300ms.
300ms is... probably still tolerable, but just barely I think. So this
PR bumps up our threshold to 500ms. We also enable logging to hopefully
get a better sense of where time is being spent.
Finally, we just to improve things by skipping the `right` and `posix`
directories in typicaly `/usr/share/zoneinfo` installations. Jiff
doesn't use them and they tend to be confusing outputs of
`TimeZoneDatabase::available()`. If users actually need those
directories, they can do `TZDIR=/usr/share/zoneinfo/posix`.
Ref #366

ci: improve tzdb init test

---

CHANGELOG.md
src/tz/db/zoneinfo/enabled.rs

Using Unix-style paths in a Windows environment doesn't really work like
you'd expect. Namely, they are interpreted relative to the current
drive. Changing which tzdb Jiff uses based on the current drive seems
undesirable. Moreover, there aren't any (AFAIK) standard locations for
the tzdb on Windows.
Note that Jiff will still respect `TZDIR` on Windows.
Fixes #376

tz: don't search for tzdb at /usr/share/zoneinfo

---

.github/workflows/ci.yml
CHANGELOG.md
examples/uptime/main.rs
scripts/test-programs
src/tz/system/mod.rs
src/tz/timezone.rs
testprograms/invalid-tz-environment-variable/Cargo.toml
testprograms/invalid-tz-environment-variable/README.md
testprograms/invalid-tz-environment-variable/main.rs

Previously, when `TZ` was set to an invalid value, Jiff would still
attempt to detect the system configured time zone. But this is arguably
not great, because it silently (aside from logs) rejects an invalid
`TZ` value. In reality, if `TZ` is set, it is likely that the user
intends for it to have an impact. So if it doesn't, we should bleat
about it.
This manifests as an error when using `TimeZone::try_system()` and
manifests as a error sentinel in the form of `Etc/Unknown` when using
`TimeZone::system()`.
We also tweak some of the logging levels. Namely, in #370, I increased
the number of TRACE-level log messages, which makes it much noisier. So
I've promoted a few things that were TRACE to DEBUG without making the
output much noisier. I guess TRACE should be reserved for variable
length …

tz: fallback to `Etc/Unknown` when `TZ` is set to an invalid value

---

COMPARE.md
src/civil/datetime.rs
src/civil/time.rs
src/fmt/friendly/mod.rs
src/fmt/strtime/mod.rs
src/fmt/temporal/mod.rs
src/signed_duration.rs
src/tz/ambiguous.rs
src/tz/mod.rs
src/tz/offset.rs
src/tz/timezone.rs

Mostly these were just unused imports in doc tests. Such warnings are
practically invisible, so they tend to sneak by.

lint: fix a variety of warnings

---

CHANGELOG.md
src/tz/timezone.rs
src/zoned.rs

In `jiff 0.1`, the fallback was to `TimeZone::UTC`, but this changed to
`TimeZone::unknown()` in `jiff 0.2`. The documentation on
`TimeZone::system()` is correct, but the docs on `TimeZone` weren't
updated.
(This change was made so that there was an error "sentinel" to indicate
something has gone wrong. This keeps routines like `Zoned::now()`
infallible.)

tz: clarify that `TimeZone::system()` falls back to `TimeZone::unknown()`

---

.github/workflows/ci.yml
Cargo.toml

This updates the allowed version range for `windows-sys` to include the
`0.61.x` release.
This also fixes CI by ensuring `rustfmt` is available when running the
`jiff-cli generate` commands. I'm unclear on why this was only failing
intermittently.

deps: allow windows-sys 0.61

---

Cargo.toml
src/civil/date.rs
src/civil/datetime.rs
src/civil/time.rs
src/fmt/serde.rs
src/signed_duration.rs
src/span.rs
src/timestamp.rs
src/zoned.rs

[serde_core](https://crates.io/crates/serde_core) has just been released. Crates that don't depend on serde derive macros should use it instead of `serde`, as it speeds up compile times by having the build for the crate itself be independent from `serde-derive` (in case it were to be enabled by some other crate). See the serde_core docs for more info.
On my Ryzen 5 5500U, building this repo with `cargo build --release --features serde` went from 10.83s to 8.76s.

serde: switch serde dependency to serde_core

---

crates/jiff-static/src/shared/posix.rs
src/shared/posix.rs

The first one here was pretty embarrassing: the parser panicked on the
empty string.
The others were a bit subtler and had to do with incorrect construction
of error messages. Arguably, more tests for the error cases here ought
to be added.
Fixes #407

shared: fix some panics in POSIX time zone parsing caught by a fuzzer
